### ISSUE TITLE
PDF Resolution (PPI)

### ISSUE THREAD

**Issue by daviss92** [ol-th/pdf-img-convert.js#35] opened 2023-01-17 14:38 UTC
How does this handle PDF Resolution? My best guess is its defaulting to 96 PPI? E.g. what if I wanted to process the PDF and convert with a resolution of 300 PPI 3in x 3in.

There can be some pretty high detailed print-ready pdf documents that can lose detail if we can't control the resolution.

**Comment by ol-th** [comment] 2023-03-05 15:02
Hi @daviss92, this is a duplicate of #22. There was some work to add a scale parameter [here](https://github.com/ol-th/pdf-img-convert.js/pull/23/files) but there are some outstanding issues with the PR.

**Closed by ol-th** 2023-03-05 15:02 UTC
